[package]
name = "fetch-all-active-and-upcoming-audits-contests"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
reqwest = "0.12.24"
scraper = "0.24.0"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
