//! Cantina Scraper – Bounties & Contests + JSON + Smart Changelog
//! Run: cargo run --bin cantina
//! Output: cantina_opportunities.json + cantina-changelog.md (only if changed)

use chrono::{DateTime, Duration, Utc};
use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};
use std::fs;
use std::io::{BufWriter, Write};
use std::error::Error;

const DATA_FILE: &str = "cantina_opportunities.json";
const CHANGELOG_FILE: &str = "cantina-changelog.md";

#[derive(Deserialize, Debug, Clone)]
struct Resp {
    items: Vec<Item>,
}

#[derive(Deserialize, Debug, Clone)]
struct Item {
    id: String,
    name: String,
    #[serde(default)]
    kind: String,
    timeframe: Timeframe,
    #[serde(default)]
    status: String,
    #[serde(rename = "currencyCode", default)]
    currency_code: String,
    #[serde(rename = "totalRewardPot", default)]
    total_reward_pot: String,
    #[serde(rename = "totalFindings", default)]
    total_findings: u32,
    #[serde(rename = "assetGroups", default)]
    asset_groups: Vec<AssetGroup>,
}

#[derive(Deserialize, Debug, Clone)]
struct Timeframe {
    start: String,
    end: Option<String>,
}

#[derive(Deserialize, Debug, Clone, Default)]
struct AssetGroup {
    #[serde(rename = "outOfScope", default)]
    out_of_scope: bool,
    #[serde(default)]
    rewards: Vec<Reward>,
}

#[derive(Deserialize, Debug, Clone)]
struct Reward {
    severity: String,
    #[serde(rename = "maxReward")]
    max_reward: Option<String>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
struct OpportunityOutput {
    id: String,
    name: String,
    kind: String,
    status: String,
    url: String,
    currency: String,
    total_reward_pot: String,
    total_findings: u32,
    start_date: String,
    end_date: Option<String>,
    time_left: Option<String>,
    accepted_severities: Vec<String>,
    reward_by_severity: HashMap<String, String>,
    last_updated: String,
}

fn main() -> Result<(), Box<dyn Error>> {
    // === Ensure files exist on first run ===
    if fs::metadata(DATA_FILE).is_err() {
        fs::write(DATA_FILE, "[]")?;
        println!("Created empty {}", DATA_FILE);
    }
    if fs::metadata(CHANGELOG_FILE).is_err() {
        let mut file = fs::File::create(CHANGELOG_FILE)?;
        writeln!(file, "# Cantina Opportunity Changelog")?;
        writeln!(file, "> Auto-generated by cantina-scraper\n")?;
        println!("Created {}", CHANGELOG_FILE);
    }

    let url = "https://api.cantina.xyz/api/v0/opportunities?limit=1000&kind=public_bounty%2Cprivate_bounty%2Cpublic_contest%2Cprivate_contest";
    let resp: Resp = reqwest::blocking::get(url)?.json()?;

    let mut bounties = Vec::new();
    let mut contests = Vec::new();

    for item in &resp.items {
        let kind_lower = item.kind.to_lowercase();
        if kind_lower.contains("bounty") {
            bounties.push(item.clone());
        } else if kind_lower.contains("contest") {
            contests.push(item.clone());
        }
    }

    bounties.sort_by_key(|i| std::cmp::Reverse(parse_date(&i.timeframe.start)));
    contests.sort_by_key(|i| {
        let start = parse_date(&i.timeframe.start);
        let end = i.timeframe.end.as_ref().map(|s| parse_date(s)).unwrap_or(start);
        std::cmp::Reverse(end - start)
    });

    let previous: HashMap<String, OpportunityOutput> = load_previous_data()?;
    let mut current_map: HashMap<String, OpportunityOutput> = HashMap::new();
    let mut changelog_entries = Vec::new();
    let now = Utc::now().to_rfc3339();
    let default_reward = "0".to_string();

    // Process Bounties
    for b in &bounties {
        let (output, changes) = process_item(b, "bounties", None, &previous, &now, &default_reward);
        current_map.insert(b.id.clone(), output.clone());
        if !changes.is_empty() {
            changelog_entries.push(format!("## [{}] {} (`{}`)\n{}", now, b.name, b.id, changes.join("\n")));
        }
        print_item(b, "bounties", None);
    }

    // Process Contests
    for c in &contests {
        let remaining = c.timeframe.end.as_ref().map(|end| {
            let end_dt = parse_date(end);
            let now_dt = Utc::now();
            if end_dt > now_dt {
                Some(format_remaining(end_dt - now_dt))
            } else {
                Some("Ended".to_string())
            }
        }).flatten();

        let (output, changes) = process_item(c, "competitions", remaining.clone(), &previous, &now, &default_reward);
        current_map.insert(c.id.clone(), output.clone());
        if !changes.is_empty() {
            changelog_entries.push(format!("## [{}] {} (`{}`)\n{}", now, c.name, c.id, changes.join("\n")));
        }
        print_item(c, "competitions", remaining);
    }

    // === Export JSON only if changed ===
    let current_vec: Vec<_> = current_map.values().cloned().collect();
    let new_json = serde_json::to_string_pretty(&current_vec)?;

    let json_changed = if fs::metadata(DATA_FILE).is_ok() {
        let old_json = fs::read_to_string(DATA_FILE)?;
        old_json != new_json
    } else {
        true
    };

    if json_changed {
        fs::write(DATA_FILE, &new_json)?;
        println!("Updated {} ({} entries)", DATA_FILE, current_vec.len());
    } else {
        println!("No changes in data. {} unchanged.", DATA_FILE);
    }

    // === Write Changelog (only if changes) ===
    if !changelog_entries.is_empty() {
        let file = fs::OpenOptions::new()
            .write(true)
            .append(true)
            .create(true)
            .open(CHANGELOG_FILE)?;

        let mut writer = BufWriter::new(file);

        // Add header only if file was empty
        if fs::metadata(CHANGELOG_FILE)?.len() == 0 {
            writeln!(writer, "# Cantina Opportunity Changelog")?;
            writeln!(writer, "> Auto-generated by cantina-scraper\n")?;
        }

        for entry in &changelog_entries {
            writeln!(writer, "{}\n", entry)?;
        }

        writer.flush()?;
        println!("{} change(s) logged to {}", changelog_entries.len(), CHANGELOG_FILE);
    } else {
        println!("No changes detected.");
    }

    Ok(())
}

fn load_previous_data() -> Result<HashMap<String, OpportunityOutput>, Box<dyn Error>> {
    let content = fs::read_to_string(DATA_FILE)?;
    let vec: Vec<OpportunityOutput> = serde_json::from_str(&content)?;
    Ok(vec.into_iter().map(|o| (o.id.clone(), o)).collect())
}

fn add_change(changes: &mut Vec<String>, field: &str, old: &str, new: &str) {
    if old != new {
        changes.push(format!("- **{}**: `{}` -> `{}`", field, old, new));
    }
}

fn process_item(
    item: &Item,
    path: &str,
    time_left: Option<String>,
    previous: &HashMap<String, OpportunityOutput>,
    now: &str,
    default_reward: &String,
) -> (OpportunityOutput, Vec<String>) {
    let url = format!("https://cantina.xyz/{}/{}", path, item.id);
    let (sevs, reward_map) = accepted_severities_and_rewards(&item.asset_groups);

    let output = OpportunityOutput {
        id: item.id.clone(),
        name: item.name.clone(),
        kind: item.kind.clone(),
        status: item.status.clone(),
        url: url.clone(),
        currency: item.currency_code.clone(),
        total_reward_pot: item.total_reward_pot.clone(),
        total_findings: item.total_findings,
        start_date: item.timeframe.start.clone(),
        end_date: item.timeframe.end.clone(),
        time_left,
        accepted_severities: sevs.clone(),
        reward_by_severity: reward_map.clone(),
        last_updated: now.to_string(),
    };

    let mut changes = Vec::new();

    if let Some(prev) = previous.get(&item.id) {
        add_change(&mut changes, "Name", &prev.name, &output.name);
        add_change(&mut changes, "Status", &prev.status, &output.status);
        add_change(&mut changes, "Reward Pot", &prev.total_reward_pot, &output.total_reward_pot);

        // Findings
        if prev.total_findings != output.total_findings {
            let diff = output.total_findings as i32 - prev.total_findings as i32;
            let sign = if diff > 0 { "+" } else { "" };
            changes.push(format!(
                "- **Findings**: `{}` -> `{}` ({}**{}**)",
                prev.total_findings, output.total_findings, sign, diff.abs()
            ));
        }

        // End date
        if prev.end_date != output.end_date {
            let old = prev.end_date.as_deref().unwrap_or("None");
            let new = output.end_date.as_deref().unwrap_or("None");
            add_change(&mut changes, "End Date", old, new);
        }

        // Rewards
        for (sev, new_rew) in &reward_map {
            let old_rew = prev.reward_by_severity.get(sev).unwrap_or(default_reward);
            if old_rew != new_rew {
                changes.push(format!("- **Reward [{}]**: `{}` -> `{}`", sev, old_rew, new_rew));
            }
        }
        for sev in prev.reward_by_severity.keys() {
            if !reward_map.contains_key(sev) {
                changes.push(format!(
                    "- **Reward [{}]**: `{}` -> `removed`",
                    sev, prev.reward_by_severity[sev]
                ));
            }
        }

        // Scope (severities)
        let prev_sevs: HashSet<_> = prev.accepted_severities.iter().collect();
        let curr_sevs: HashSet<_> = sevs.iter().collect();

        for sev in curr_sevs.difference(&prev_sevs) {
            changes.push(format!("- **New Scope**: `{}`", sev));
        }
        for sev in prev_sevs.difference(&curr_sevs) {
            changes.push(format!("- **Removed Scope**: `{}`", sev));
        }
    } else {
        changes.push("- **NEW OPPORTUNITY ADDED**".to_string());
    }

    (output, changes)
}

fn parse_date(s: &str) -> DateTime<Utc> {
    DateTime::parse_from_rfc3339(s)
        .map(|dt| dt.with_timezone(&Utc))
        .unwrap_or_else(|_| Utc::now())
}

fn format_remaining(dur: Duration) -> String {
    let days = dur.num_days();
    let hours = dur.num_hours() % 24;
    let minutes = dur.num_minutes() % 60;

    if days > 0 {
        format!("{} days {}h {}m left", days, hours, minutes)
    } else if hours > 0 {
        format!("{}h {}m left", hours, minutes)
    } else {
        format!("{}m left", minutes)
    }
}

fn accepted_severities_and_rewards(groups: &[AssetGroup]) -> (Vec<String>, HashMap<String, String>) {
    let mut sev_set = HashSet::new();
    let mut reward_map = HashMap::new();

    for g in groups {
        if g.out_of_scope { continue; }
        for r in &g.rewards {
            if let Some(max) = &r.max_reward {
                let max_str = max.trim();
                if !max_str.is_empty() && max_str != "0" && max_str != "0.00" {
                    sev_set.insert(r.severity.clone());
                    reward_map.insert(r.severity.clone(), max_str.to_string());
                }
            }
        }
    }

    let mut sevs: Vec<_> = sev_set.into_iter().collect();
    sevs.sort_unstable();
    (sevs, reward_map)
}

fn print_item(i: &Item, path: &str, remaining: Option<String>) {
    let url = format!("https://cantina.xyz/{}/{}", path, i.id);
    let sevs = accepted_severities_and_rewards(&i.asset_groups).0;

    println!("Name: {}", i.name);
    println!("Kind: {}", i.kind);
    println!("Start: {}", i.timeframe.start);
    if let Some(end) = &i.timeframe.end {
        println!("End:   {}", end);
    }
    if let Some(rem) = remaining {
        println!("Time Left: {}", rem);
    }
    println!("URL: {}", url);
    println!("Status: {}", i.status);
    println!("Currency: {}", i.currency_code);
    println!("Total Reward Pot: {}", i.total_reward_pot);
    println!(
        "Accepted Severities: {}",
        if sevs.is_empty() { "None".to_string() } else { sevs.join(", ") }
    );
    println!("Total Findings: {}", i.total_findings);
    println!("---");
}