//! Immunefi Scraper – Scope + Rewards + JSON + Smart Changelog
//! Run: cargo run --bin immunefi
//! Output: immunefi_programs.json + immunefi-changelog.md (only if changed)

use reqwest::blocking::get;
use scraper::{Html, Selector};
use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};
use std::error::Error;
use std::fs;
use std::io::{BufWriter, Write};
use chrono::Utc;

const DATA_FILE: &str = "immunefi/immunefi_programs.json";
const CHANGELOG_FILE: &str = "immunefi/immunefi-changelog.md";

#[derive(Deserialize, Debug)]
struct ListData {
    props: ListProps,
}
#[derive(Deserialize, Debug)]
struct ListProps {
    #[serde(rename = "pageProps")]
    page_props: ListPageProps,
}
#[derive(Deserialize, Debug)]
struct ListPageProps {
    bounties: Vec<ListBounty>,
}

#[derive(Deserialize, Debug, Clone)]
struct ListBounty {
    id: String,
    project: String,
    #[serde(rename = "maximum_reward")]
    max_bounty: u64,
    #[serde(rename = "vaultBalance")]
    vault_balance: Option<f64>,
    tags: Tags,
}

#[derive(Deserialize, Debug, Clone)]
struct Tags {
    language: Vec<String>,
    #[serde(rename = "productType")]
    product_type: Vec<String>,
    #[serde(rename = "programType")]
    program_type: Vec<String>,
    #[serde(rename = "projectType")]
    project_type: Vec<String>,
}

#[derive(Deserialize, Debug)]
struct DetailData {
    props: DetailProps,
}
#[derive(Deserialize, Debug)]
struct DetailProps {
    #[serde(rename = "pageProps")]
    page_props: DetailPageProps,
}
#[derive(Deserialize, Debug)]
struct DetailPageProps {
    bounty: DetailBounty,
}
#[derive(Deserialize, Debug)]
struct DetailBounty {
    assets: Vec<Asset>,
    rewards: Vec<Reward>,
    legacy: Option<LegacyRewards>,
}

#[derive(Deserialize, Debug)]
struct Asset {
    #[serde(rename = "type")]
    asset_type: String,
    url: String,
    description: Option<String>,
}

#[derive(Deserialize, Debug)]
struct Reward {
    severity: String,
    #[serde(rename = "fixedReward")]
    fixed_reward: Option<u64>,
    #[serde(rename = "maxReward")]
    max_reward: Option<u64>,
    #[serde(rename = "rewardModel")]
    reward_model: String,
}

#[derive(Deserialize, Debug)]
struct LegacyRewards {
    #[serde(rename = "smartcontract_rewards")]
    smart_contract: Option<Vec<LegacyReward>>,
    #[serde(rename = "web_rewards")]
    web: Option<Vec<LegacyReward>>,
}

#[derive(Deserialize, Debug)]
struct LegacyReward {
    level: String,
    payout: String,
}

// === Final Output Struct ===
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
struct ProgramOutput {
    id: String,
    name: String,
    max_bounty: String,
    vault_tvl: String,
    detail_url: String,
    smart_contract_bounties: HashMap<String, String>,
    web_bounties: HashMap<String, String>,
    unified_bounties: HashMap<String, String>,
    github_repos: Vec<String>,
    onchain_contracts: Vec<String>,
    has_web_scope: bool,
    has_github: bool,
    last_updated: String,
}

#[derive(Default, Debug)]
struct Program {
    id: String,
    name: String,
    max_bounty: String,
    vault_tvl: String,
    detail_url: String,
    smart_contract_rewards: HashMap<String, String>,
    web_rewards: HashMap<String, String>,
    rewards: HashMap<String, String>,
    github_links: Vec<String>,
    onchain_links: Vec<String>,
    has_github: bool,
    has_web_scope: bool,
}

fn main() -> Result<(), Box<dyn Error>> {
    // === Ensure files exist on first run ===
    if fs::metadata(DATA_FILE).is_err() {
        fs::write(DATA_FILE, "[]")?;
        println!("Created empty {}", DATA_FILE);
    }
    if fs::metadata(CHANGELOG_FILE).is_err() {
        let mut file = fs::File::create(CHANGELOG_FILE)?;
        writeln!(file, "# Immunefi Bug Bounty Changelog")?;
        writeln!(file, "> Auto-generated by immunefi-scraper\n")?;
        println!("Created {}", CHANGELOG_FILE);
    }

    let list_url = "https://immunefi.com/bug-bounty/?filter=language%3DSolidity%26projectType%3DDefi%26productType%3DStablecoin&sort=maximum_reward%3Aasc";
    let body = get(list_url)?.text()?;
    let doc = Html::parse_document(&body);

    let script_sel = Selector::parse(r#"script[id="__NEXT_DATA__"]"#).unwrap();
    let script = doc.select(&script_sel).next().ok_or("No __NEXT_DATA__")?;
    let json_text = script.inner_html();
    let list_data: ListData = serde_json::from_str(&json_text)?;

    // Load previous data
    let previous: HashMap<String, ProgramOutput> = load_previous_data()?;
    let mut current_map: HashMap<String, ProgramOutput> = HashMap::new();
    let mut changelog_entries = Vec::new();
    let now = Utc::now().to_rfc3339();
    let default_reward = "0".to_string();

    let mut programs = Vec::new();

    for bounty in &list_data.props.page_props.bounties {
        if !matches_filter(&bounty.tags) {
            continue;
        }

        let detail_url = format!("https://immunefi.com/bounty/{}/", bounty.id);
        let vault_str = bounty.vault_balance
            .map(|v| format!("${:.1}k", v / 1000.0))
            .unwrap_or_else(|| if bounty.max_bounty > 0 { "Private".to_string() } else { "None".to_string() });

        let mut p = Program {
            id: bounty.id.clone(),
            name: bounty.project.clone(),
            max_bounty: format!("${}", format_number(bounty.max_bounty)),
            vault_tvl: vault_str,
            detail_url: detail_url.clone(),
            ..Default::default()
        };

        if let Ok(detail_json) = fetch_detail_json(&detail_url) {
            let bounty_detail = &detail_json.props.page_props.bounty;

            // Scope
            for asset in &bounty_detail.assets {
                if !["smart_contract", "web"].contains(&asset.asset_type.as_str()) {
                    continue;
                }

                let line = asset.description.as_ref()
                    .and_then(|d| if d.trim().is_empty() { None } else { Some(d.trim().to_string()) })
                    .map(|d| format!("{} -> {}", d, asset.url))
                    .unwrap_or(asset.url.clone());

                match asset.asset_type.as_str() {
                    "web" => p.has_web_scope = true,
                    _ => {
                        if asset.url.contains("github.com") {
                            p.github_links.push(line.clone());
                            p.has_github = true;
                        } else if asset.url.contains("etherscan")
                            || asset.url.contains("bscscan")
                            || asset.url.contains("blockscout")
                        {
                            p.onchain_links.push(line);
                        }
                    }
                }
            }

            // Rewards
            if let Some(legacy) = &bounty_detail.legacy {
                if let Some(sc) = &legacy.smart_contract {
                    for r in sc {
                        if let Some(sev) = map_severity(&r.level) {
                            p.smart_contract_rewards.insert(sev.to_string(), r.payout.clone());
                        }
                    }
                }
                if let Some(web) = &legacy.web {
                    for r in web {
                        if let Some(sev) = map_severity(&r.level) {
                            p.web_rewards.insert(sev.to_string(), r.payout.clone());
                        }
                    }
                }
            }

            if p.smart_contract_rewards.is_empty() && p.web_rewards.is_empty() {
                for reward in &bounty_detail.rewards {
                    if let Some(sev) = map_severity(&reward.severity) {
                        let rew = if let Some(fixed) = reward.fixed_reward {
                            format!("${}", format_number(fixed))
                        } else if let Some(max) = reward.max_reward {
                            if reward.reward_model == "up_to" {
                                format!("up to ${}", format_number(max))
                            } else {
                                format!("${}", format_number(max))
                            }
                        } else {
                            continue;
                        };
                        p.rewards.insert(sev.to_string(), rew);
                    }
                }
            }
        }

        let output = ProgramOutput {
            id: p.id.clone(),
            name: p.name.clone(),
            max_bounty: p.max_bounty.clone(),
            vault_tvl: p.vault_tvl.clone(),
            detail_url: p.detail_url.clone(),
            smart_contract_bounties: p.smart_contract_rewards.clone(),
            web_bounties: p.web_rewards.clone(),
            unified_bounties: p.rewards.clone(),
            github_repos: p.github_links.clone(),
            onchain_contracts: p.onchain_links.clone(),
            has_web_scope: p.has_web_scope,
            has_github: p.has_github,
            last_updated: now.clone(),
        };

        // Diff and log changes
        let changes = diff_program(&p.id, &previous, &output, &default_reward);
        if !changes.is_empty() {
            let header = format!("## [{}] {} (`{}`)", now, p.name, p.id);
            changelog_entries.push(format!("{}\n{}", header, changes.join("\n")));
        }

        current_map.insert(p.id.clone(), output);
        programs.push(p);
    }

    if programs.is_empty() {
        println!("No programs match filters.");
        return Ok(());
    }

    // Sort by max bounty
    programs.sort_by_key(|p| parse_amount(&p.max_bounty));

    // === Export JSON only if changed ===
    let new_json_vec: Vec<_> = current_map.values().cloned().collect();
    let new_json_str = serde_json::to_string_pretty(&new_json_vec)?;

    let json_changed = if fs::metadata(DATA_FILE).is_ok() {
        let old_json = fs::read_to_string(DATA_FILE)?;
        old_json != new_json_str
    } else {
        true
    };

    if json_changed {
        fs::write(DATA_FILE, &new_json_str)?;
        println!("Updated {} ({} programs)", DATA_FILE, new_json_vec.len());
    } else {
        println!("No changes in data. {} unchanged.", DATA_FILE);
    }

    // === Write Changelog (with robust error handling) ===
    if !changelog_entries.is_empty() {
        let file = fs::OpenOptions::new()
            .write(true)
            .append(true)
            .create(true)
            .open(CHANGELOG_FILE)?;

        let mut writer = BufWriter::new(file);

        // Add header only if file was empty
        if fs::metadata(CHANGELOG_FILE)?.len() == 0 {
            writeln!(writer, "# Immunefi Bug Bounty Changelog")?;
            writeln!(writer, "> Auto-generated by immunefi-scraper\n")?;
        }

        for entry in &changelog_entries {
            writeln!(writer, "{}\n", entry)?;
        }

        writer.flush()?;
        println!("{} change(s) logged to {}", changelog_entries.len(), CHANGELOG_FILE);
    } else {
        println!("No changes detected.");
    }

    // === Console Output ===
    println!("=== IMMUNEFI BOUNTY PROGRAMS ({})\n", programs.len());
    for prog in &programs {
        print_summary(prog);
        print_rewards(prog);
        print_scope(prog);
        println!("---\n");
    }
    println!("Visualize the json on -->  https://jsontotable.org/");
    Ok(())
}

// ---------------------------------------------------------------------
// Diff Engine
// ---------------------------------------------------------------------
fn diff_program(
    id: &str,
    previous: &HashMap<String, ProgramOutput>,
    current: &ProgramOutput,
    default_reward: &String,
) -> Vec<String> {
    let mut changes = Vec::new();

    match previous.get(id) {
        Some(prev) => {
            if prev.name != current.name { changes.push(format!("- **Name**: `{}` -> `{}`", prev.name, current.name)); }
            if prev.max_bounty != current.max_bounty { changes.push(format!("- **Max Bounty**: `{}` -> `{}`", prev.max_bounty, current.max_bounty)); }
            if prev.vault_tvl != current.vault_tvl { changes.push(format!("- **Vault TVL**: `{}` -> `{}`", prev.vault_tvl, current.vault_tvl)); }

            diff_rewards(&prev.smart_contract_bounties, &current.smart_contract_bounties, "Smart Contract", &mut changes, default_reward);
            diff_rewards(&prev.web_bounties, &current.web_bounties, "Web", &mut changes, default_reward);
            diff_rewards(&prev.unified_bounties, &current.unified_bounties, "Unified", &mut changes, default_reward);

            diff_vec(&prev.github_repos, &current.github_repos, "GitHub Repo", &mut changes);
            diff_vec(&prev.onchain_contracts, &current.onchain_contracts, "On-Chain Contract", &mut changes);

            if prev.has_web_scope != current.has_web_scope {
                changes.push(format!("- **Web Scope**: {} -> {}", prev.has_web_scope, current.has_web_scope));
            }
            if prev.has_github != current.has_github {
                changes.push(format!("- **GitHub Scope**: {} -> {}", prev.has_github, current.has_github));
            }
        }
        None => {
            changes.push("- **NEW PROGRAM ADDED**".to_string());
        }
    }

    changes
}

fn diff_rewards(old: &HashMap<String, String>, new: &HashMap<String, String>, kind: &str, changes: &mut Vec<String>, default: &String) {
    for (sev, new_rew) in new {
        let old_rew = old.get(sev).unwrap_or(default);
        if old_rew != new_rew {
            changes.push(format!("- **{} [{}]**: `{}` -> `{}`", kind, sev, old_rew, new_rew));
        }
    }
    for sev in old.keys() {
        if !new.contains_key(sev) {
            changes.push(format!("- **{} [{}]**: `{}` -> `removed`", kind, sev, old[sev]));
        }
    }
}

fn diff_vec(old: &[String], new: &[String], kind: &str, changes: &mut Vec<String>) {
    let old_set: HashSet<_> = old.iter().collect();
    let new_set: HashSet<_> = new.iter().collect();

    for added in new_set.difference(&old_set) {
        changes.push(format!("- **New {}**: `{}`", kind, added));
    }
    for removed in old_set.difference(&new_set) {
        changes.push(format!("- **Removed {}**: `{}`", kind, removed));
    }
}

// ---------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------
fn load_previous_data() -> Result<HashMap<String, ProgramOutput>, Box<dyn Error>> {
    let content = fs::read_to_string(DATA_FILE)?;
    let vec: Vec<ProgramOutput> = serde_json::from_str(&content)?;
    Ok(vec.into_iter().map(|o| (o.id.clone(), o)).collect())
}

fn matches_filter(tags: &Tags) -> bool {
    tags.language.iter().any(|l| l == "Solidity")
        && tags.project_type.iter().any(|t| t == "Defi")
        && tags.program_type.iter().any(|t| t == "Smart Contract")
        && tags.product_type.iter().any(|t| t == "Stablecoin")
}

fn fetch_detail_json(url: &str) -> Result<DetailData, Box<dyn Error>> {
    let body = get(url)?.text()?;
    let doc = Html::parse_document(&body);
    let script = doc.select(&Selector::parse(r#"script[id="__NEXT_DATA__"]"#).unwrap())
        .next().ok_or("No __NEXT_DATA__ on detail page")?;
    let json_text = script.inner_html();
    Ok(serde_json::from_str(&json_text)?)
}

fn format_number(n: u64) -> String {
    if n >= 1_000_000 {
        format!("{}M", n / 1_000_000)
    } else if n >= 1_000 {
        format!("{}k", n / 1_000)
    } else {
        n.to_string()
    }
}

fn parse_amount(s: &str) -> i64 {
    let s = s.replace(['$', ','], "").to_lowercase();
    let num: f64 = s.chars()
        .filter(|c| c.is_ascii_digit() || *c == '.')
        .collect::<String>()
        .parse()
        .unwrap_or(0.0);
    if s.contains('m') {
        (num * 1_000_000.0) as i64
    } else if s.contains('k') {
        (num * 1_000.0) as i64
    } else {
        num as i64
    }
}

fn map_severity(s: &str) -> Option<&'static str> {
    match s.to_lowercase().as_str() {
        "critical" => Some("Critical"),
        "high" => Some("High"),
        "medium" => Some("Medium"),
        "low" => Some("Low"),
        _ => None,
    }
}

// ---------------------------------------------------------------------
// Console Printing
// ---------------------------------------------------------------------
fn print_summary(p: &Program) {
    println!("Name: {}", p.name);
    println!("Max Bounty: {}", p.max_bounty);
    println!("Vault TVL: {}", p.vault_tvl);
    println!("Detail URL: {}", p.detail_url);
}

fn print_rewards(p: &Program) {
    let has_legacy = !p.smart_contract_rewards.is_empty() || !p.web_rewards.is_empty();
    let has_modern = !p.rewards.is_empty();

    if !has_legacy && !has_modern {
        println!("Rewards: Not specified");
        return;
    }

    if has_legacy {
        if !p.smart_contract_rewards.is_empty() {
            println!("Smart Contract Bounties:");
            for sev in &["Critical", "High", "Medium", "Low"] {
                if let Some(rew) = p.smart_contract_rewards.get(*sev) {
                    println!("  {}: {}", sev, rew);
                }
            }
        }
        if !p.web_rewards.is_empty() {
            println!("Websites & Applications Bounties:");
            for sev in &["Critical", "High", "Medium", "Low"] {
                if let Some(rew) = p.web_rewards.get(*sev) {
                    println!("  {}: {}", sev, rew);
                }
            }
        }
    } else if has_modern {
        println!("Bounties (Unified):");
        for sev in &["Critical", "High", "Medium", "Low"] {
            if let Some(rew) = p.rewards.get(*sev) {
                println!("  {}: {}", sev, rew);
            }
        }
    }
}

fn print_scope(p: &Program) {
    if p.github_links.is_empty() && p.onchain_links.is_empty() && !p.has_web_scope {
        println!("Scope: Not specified");
        return;
    }

    if !p.github_links.is_empty() {
        println!("GitHub: Yes ({} repo(s))", p.github_links.len());
        for link in &p.github_links {
            println!("  - {}", link);
        }
    }

    if !p.onchain_links.is_empty() {
        println!("On-Chain: Yes ({} contract(s))", p.onchain_links.len());
        for link in &p.onchain_links {
            println!("  - {}", link);
        }
    }

    if p.has_web_scope {
        println!("Web Scope: Yes");
    }

    if p.github_links.is_empty() && !p.onchain_links.is_empty() {
        println!("No GitHub — on-chain audit only.");
    }
}